/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemasystem;

import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

import CinemaClasses.Film;
import CinemaClasses.JTextFieldLimit;
import net.proteanit.sql.DbUtils;

import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author christophermclaughlin
 */
public class AddFilm extends javax.swing.JFrame {
	
	private final String USER_NAME = "root";
	private final String PASSWORD = "password";
    Connection conn;
    Statement st;
    ResultSet rs;
	String ImagePath ="";
	//File image = new File(ImagePath);
    /**
     * Creates new form AddFilm
     */
    public AddFilm() {
    	getContentPane().setBackground(new Color(0, 204, 204));
    	setBackground(Color.WHITE);
    	getContentPane().setForeground(Color.WHITE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TitleTextField1 = new javax.swing.JTextField();
        TitleTextField1.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        TitleLabel = new javax.swing.JLabel();
        TitleLabel.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        addBt = new javax.swing.JButton();
        addBt.setBackground(new Color(102, 204, 0));
        addBt.setFont(new Font("Lucida Grande", Font.PLAIN, 32));
        Cancel = new javax.swing.JButton();
        Cancel.setBackground(new Color(204, 51, 51));
        Cancel.setFont(new Font("Lucida Grande", Font.PLAIN, 32));
        PgRatingLabel = new javax.swing.JLabel();
        PgRatingLabel.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        GenreLabel = new javax.swing.JLabel();
        GenreLabel.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        PgRatingCB = new javax.swing.JComboBox<>();
        PgRatingCB.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        GenrejTextField = new javax.swing.JTextField();
        GenrejTextField.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        DurationjTextField = new javax.swing.JTextField();
        DurationjTextField.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        DurationLabel = new javax.swing.JLabel();
        DurationLabel.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        ActorjTextField = new javax.swing.JTextField();
        ActorjTextField.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        ActorLabel = new javax.swing.JLabel();
        ActorLabel.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        DirectorjTextField = new javax.swing.JTextField();
        DirectorjTextField.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        DirectorLabel = new javax.swing.JLabel();
        DirectorLabel.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        LinkLabel = new javax.swing.JLabel();
        LinkLabel.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        LinkjTextField = new javax.swing.JTextField();
        LinkjTextField.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new Font("American Typewriter", Font.BOLD, 50)); // NOI18N
        jLabel1.setForeground(Color.RED);
        jLabel1.setText("Add Film");

        TitleTextField1.setForeground(new java.awt.Color(204, 204, 204));
        TitleTextField1.setText("Film Title");

        TitleLabel.setText("Film Title");

        addBt.setText("Add");
        
      /*  browse.setText("Browse");
        browse.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		browseBTActionPerformed(e);
        	}
        });*/
        
        addBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        
        TitleTextField1.addFocusListener(new FocusListener() {
        	public void focusGained(FocusEvent e) {
        		titleTFfocusGained(e);
        
        	}

			@Override
			public void focusLost(FocusEvent e) {
				titleTFfocusLost(e);
				
			}
        });
        
        GenrejTextField.addFocusListener(new FocusListener() {
        	public void focusGained(FocusEvent e) {
        		genreTFfocusGained(e);
        
        	}

			@Override
			public void focusLost(FocusEvent e) {
				genreTFfocusLost(e);
				
			}
        });
        
        DurationjTextField.addFocusListener(new FocusListener() {
        	public void focusGained(FocusEvent e) {
        		durationTFfocusGained(e);
        
        	}

			@Override
			public void focusLost(FocusEvent e) {
				durationTFfocusLost(e);
				
			}
        });

        ActorjTextField.addFocusListener(new FocusListener() {
        	public void focusGained(FocusEvent e) {
        		actorTFfocusGained(e);
        
        	}

			@Override
			public void focusLost(FocusEvent e) {
				actorTFfocusLost(e);
				
			}
        });
        
        DirectorjTextField.addFocusListener(new FocusListener() {
        	public void focusGained(FocusEvent e) {
        		directorTFfocusGained(e);
        
        	}

			@Override
			public void focusLost(FocusEvent e) {
				directorTFfocusLost(e);
				
			}
        });
        
        LinkjTextField.addFocusListener(new FocusListener() {
        	public void focusGained(FocusEvent e) {
        		ytTFfocusGained(e);
        
        	}

			@Override
			public void focusLost(FocusEvent e) {
				ytTFfocusLost(e);
				
			}
        });
        
        DurationjTextField.addKeyListener(new KeyListener() {
        	public void keyTyped(KeyEvent e) {
        		durationTFkeyTyped(e);
        	}

			@Override
			public void keyPressed(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void keyReleased(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}
        });
        
        PgRatingLabel.setText("PG - Rating");

        GenreLabel.setText("Genre");

       // PgRatingCB.setForeground(new java.awt.Color(204, 204, 204));
        PgRatingCB.setModel(new DefaultComboBoxModel<>(new String[] {"Select Rating", "U", "PG", "12A", "12", "15", "15A", "18"}));

        GenrejTextField.setForeground(new java.awt.Color(204, 204, 204));
        GenrejTextField.setText("Genre");

        DurationjTextField.setDocument(new JTextFieldLimit(3));
        DurationjTextField.setForeground(new java.awt.Color(204, 204, 204));
        DurationjTextField.setText("Min");

        DurationLabel.setText("Duration (mins)");

        ActorjTextField.setForeground(new java.awt.Color(204, 204, 204));
        ActorjTextField.setText("Actor");

        ActorLabel.setText("Actor");
        
        DirectorjTextField.setForeground(new java.awt.Color(204, 204, 204));
        DirectorjTextField.setText("Director");

        DirectorLabel.setText("Director");

        LinkLabel.setText("Trailer");

        LinkjTextField.setForeground(new java.awt.Color(204, 204, 204));
        LinkjTextField.setText("Trailer Link");
        
        JLabel lblNewLabel = new JLabel("Synopsis");
        lblNewLabel.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        
        txtSynopsis = new JTextField();
        txtSynopsis.setForeground(Color.LIGHT_GRAY);
        txtSynopsis.setFont(new Font("Lucida Grande", Font.PLAIN, 39));
        txtSynopsis.setText("Synopsis");
        txtSynopsis.setColumns(10);
        
        txtSynopsis.addFocusListener(new FocusListener() {
        	public void focusGained(FocusEvent e) {
        		synopsisTFfocusGained(e);
        
        	}

			@Override
			public void focusLost(FocusEvent e) {
				synopsisTFfocusLost(e);
				
			}
        });
        
        JButton browse = new JButton("Add Poster");
        browse.setBackground(new Color(102, 204, 0));
        browse.setFont(new Font("Lucida Grande", Font.PLAIN, 32));
        browse.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		browseBTActionPerformed(e);
        	}
        });
        
        
        
        JLabel lblNewLabel_1 = new JLabel("Poster");
        lblNewLabel_1.setFont(new Font("Lucida Grande", Font.PLAIN, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(TitleLabel, GroupLayout.PREFERRED_SIZE, 220, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(GenreLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addGap(117))
        							.addComponent(PgRatingLabel, GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(DirectorLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addGap(83))
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(ActorLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addGap(134))
        							.addComponent(DurationLabel, GroupLayout.PREFERRED_SIZE, 305, GroupLayout.PREFERRED_SIZE)
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(LinkLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addGap(45)))
        						.addComponent(lblNewLabel)
        						.addComponent(lblNewLabel_1))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(txtSynopsis, GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        						.addComponent(PgRatingCB, 0, 842, Short.MAX_VALUE)
        						.addComponent(GenrejTextField, 842, 842, Short.MAX_VALUE)
        						.addComponent(DurationjTextField, 842, 842, Short.MAX_VALUE)
        						.addComponent(ActorjTextField, 842, 842, Short.MAX_VALUE)
        						.addComponent(DirectorjTextField, 842, 842, Short.MAX_VALUE)
        						.addComponent(LinkjTextField, GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        						.addComponent(TitleTextField1, GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(browse)
        							.addPreferredGap(ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
        							.addComponent(Cancel, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(addBt, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)))
        					.addGap(42))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(577)
        					.addComponent(jLabel1)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(24)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(TitleLabel)
        				.addComponent(TitleTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(PgRatingCB, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE)
        				.addComponent(PgRatingLabel, GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(GenreLabel)
        				.addComponent(GenrejTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(DurationLabel)
        				.addComponent(DurationjTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(ActorjTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(ActorLabel))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(DirectorLabel)
        				.addComponent(DirectorjTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(LinkLabel)
        				.addComponent(LinkjTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtSynopsis, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNewLabel))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(12)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(Cancel, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        						.addComponent(addBt, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblNewLabel_1)
        						.addComponent(browse))))
        			.addGap(7))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
       JComponent comp = (JComponent) evt.getSource();
         Window win = SwingUtilities.getWindowAncestor(comp);
         win.dispose(); 
    }//GEN-LAST:event_CancelActionPerformed
    
    private void addBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
       String title, rating, genre, durationString, actor, director, ytLink, synopsis;
       int duration = 0;
       InputStream poster = null;
       title = TitleTextField1.getText();
       rating = PgRatingCB.getSelectedItem().toString();
   	   genre = GenrejTextField.getText();
   	   durationString = DurationjTextField.getText();
   	   synopsis = txtSynopsis.getText();
   	   try {
   		duration = Integer.parseInt(durationString);
   	   }catch(Exception e) {
      
   	   }
   	  // duration = Integer.parseInt(durationString);
   	   actor = ActorjTextField.getText();
   	   director = DirectorjTextField.getText();
   	   ytLink = LinkjTextField.getText();
   	   
   	   if(title.equals("Film Title")) {
   		JOptionPane.showMessageDialog(null,  "Please enter a vaild Film Title");
   	   }
   	   else if(rating.equals("Select Rating")) {
   		JOptionPane.showMessageDialog(null,  "Please enter a vaild Rating");
   	   }
   	   else if(genre.equals("Genre")) {
   		JOptionPane.showMessageDialog(null,  "Please enter a vaild Genre");
   	   }
   	   else if(durationString.equals("Min") || duration < 60 || duration > 300) {
   		JOptionPane.showMessageDialog(null,  "Please enter a vaild Duration\nPlease note films are never shorter than 60 minutes\nor longer than 300 minutes");
   	   }
   	   else if(actor.equals("Actor")) {
   		JOptionPane.showMessageDialog(null,  "Please enter vaild Actor/s name");
   	   }
   	   else if(ytLink.equals("Trailer Link")) {
   		JOptionPane.showMessageDialog(null,  "Please enter a vaild Trailer Link");
   	   }
   	  else if(synopsis.equals("")){
          JOptionPane.showMessageDialog(null,  "Please enter a synopsis");

     	   }
   	   else if(ImagePath.equals("Synopsis")) {
      	JOptionPane.showMessageDialog(null,  "Please add a vaild Poster");

   	   }
   	   else { 
   		   try {
   	//	poster = new FileInputStream(image);
   		   }
   		   catch(Exception e) {
   			   
   		   }
   		   
   		try {
   			InputStream is = new FileInputStream(new File(ImagePath));
    		conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", USER_NAME, PASSWORD);
    		PreparedStatement ps = conn.prepareStatement("Insert into film() values(?, ?, ?, ?, ?, ?, ?, ?, ?)");
    		ps.setString(1,  title);
    		ps.setString(2,  rating);
    		ps.setString(3,  genre);
    		ps.setInt(4,  duration);
    		ps.setString(5,  actor);
    		ps.setString(6,  director);
    		ps.setString(7,  ytLink);
    		ps.setBlob(8,  is);
    		ps.setString(9,  synopsis);
    		ps.executeUpdate();

 		}
 		catch (Exception a) {
 		JOptionPane.showMessageDialog(null,  "Error");
 		}finally {
 			try {
 				conn.close();
 				
 			}catch(Exception a) {
 	    		JOptionPane.showMessageDialog(null,  "Error Close");

 			}
 		}
   		
   		JOptionPane.showMessageDialog(null,  "Film sucessfull added");

   	   }
    }
    
    private void browseBTActionPerformed(ActionEvent e) {
    	JFileChooser fileChooser = new JFileChooser();
    	fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
    	FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "gif", "png");
    	fileChooser.addChoosableFileFilter(filter);
    	int result = fileChooser.showSaveDialog(null);
    	if(result == JFileChooser.APPROVE_OPTION) {
    		File selectedFile = fileChooser.getSelectedFile();
    		String path = selectedFile.getAbsolutePath();
    		ImagePath = path;
    		
    	}
    }
    
    private void titleTFfocusGained(FocusEvent e) {
    	if(TitleTextField1.getText().equals("Film Title")) {
    		TitleTextField1.setText("");
    	}
    	
    }
    
    private void titleTFfocusLost(FocusEvent e) {
    	if(TitleTextField1.getText().equals("")) {
    		TitleTextField1.setText("Film Title");
    	}
    	
    }
    
  
    
    private void genreTFfocusGained(FocusEvent e) {
    	if(GenrejTextField.getText().equals("Genre")) {
    		GenrejTextField.setText("");
    	}
    	
    }
    
    private void genreTFfocusLost(FocusEvent e) {
    	if(GenrejTextField.getText().equals("")) {
    		GenrejTextField.setText("Genre");
    	}
    	
    }
    
    private void durationTFfocusGained(FocusEvent e) {
    	if(DurationjTextField.getText().equals("Min")) {
    		DurationjTextField.setText("");
    	}
    	
    }
    
    private void durationTFfocusLost(FocusEvent e) {
    	if(DurationjTextField.getText().equals("")) {
    		DurationjTextField.setText("Min");
    	}
    	
    }
    
    private void actorTFfocusGained(FocusEvent e) {
    	if(ActorjTextField.getText().equals("Actor")) {
    		ActorjTextField.setText("");
    	}
    	
    }
    
    private void actorTFfocusLost(FocusEvent e) {
    	if(ActorjTextField.getText().equals("")) {
    		ActorjTextField.setText("Actor");
    	}
    	
    }
    
    private void directorTFfocusGained(FocusEvent e) {
    	if(DirectorjTextField.getText().equals("Director")) {
    		DirectorjTextField.setText("");
    	}
    	
    }
    
    private void directorTFfocusLost(FocusEvent e) {
    	if(DirectorjTextField.getText().equals("")) {
    		DirectorjTextField.setText("Director");
    	}
    	
    }


    private void ytTFfocusGained(FocusEvent e) {
    	if(LinkjTextField.getText().equals("Trailer Link")) {
    		LinkjTextField.setText("");
    	}
    	
    }
    
    private void ytTFfocusLost(FocusEvent e) {
    	if(LinkjTextField.getText().equals("")) {
    		LinkjTextField.setText("Trailer Link");
    	}
    }
    
    
    private void synopsisTFfocusGained(FocusEvent e) {
    	if(txtSynopsis.getText().equals("Synopsis")) {
    		txtSynopsis.setText("");
    	}
    	
    }
    
    private void synopsisTFfocusLost(FocusEvent e) {
    	if(txtSynopsis.getText().equals("")) {
    		txtSynopsis.setText("Synopsis");
    	}
    }
    private void durationTFkeyTyped(KeyEvent e) {
    	char c = e.getKeyChar();
    	if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE) {
    		e.consume();
    	}
    	
    }
    	
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	AddFilm frame = new AddFilm();
                
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH); 
                
                frame.setVisible(true);    
            	
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActorLabel;
    private javax.swing.JTextField ActorjTextField;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel DirectorLabel;
    private javax.swing.JTextField DirectorjTextField;
    private javax.swing.JLabel DurationLabel;
    private javax.swing.JTextField DurationjTextField;
    private javax.swing.JLabel GenreLabel;
    private javax.swing.JTextField GenrejTextField;
    private javax.swing.JLabel LinkLabel;
    private javax.swing.JTextField LinkjTextField;
    private javax.swing.JLabel PgRatingLabel;
    private javax.swing.JComboBox PgRatingCB;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField TitleTextField1;
    private javax.swing.JButton addBt;
    private javax.swing.JLabel jLabel1;
    private JTextField txtSynopsis;
}
