package cinemasystem;

import java.awt.Window;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author christophermclaughlin
 */
public class EditAdmin extends javax.swing.JFrame {

	
	private final String USER_NAME = "root";
	private final String PASSWORD = "password";
    Connection conn;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form EditAdmin
     */
    public EditAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        administratorsLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        editButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		EditAdministrator editAdmin1 = new EditAdministrator();
          	  editAdmin1.setExtendedState(JFrame.MAXIMIZED_BOTH); 
                editAdmin1.setVisible(true);
        	}
        });
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        adminCBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        administratorsLabel.setFont(new java.awt.Font("Lucida Grande", 0, 39)); // NOI18N
        administratorsLabel.setText("Administrators");

        editButton.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        deleteButton.setText("Delete");

        addButton.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        addButton.setText("Add");

        adminCBox.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        //adminCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "It", "Item 3", "Item 4" }));
        adminCBox.setModel(new DefaultComboBoxModel<>(new String[] {"Select Administrator"}));
        
        try {
			conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema?autoReconnect=true&useSSL=false", USER_NAME, PASSWORD);
			st = conn.createStatement();
			String s = "Select adminName from admins";
			rs = st.executeQuery(s);
			while(rs.next()) {
				adminCBox.addItem(rs.getString(1));
			}
		}
		catch (Exception b) {
		JOptionPane.showMessageDialog(null,  "Error");
		}finally {
			try {
				st.close();
				rs.close();
				conn.close();
				
			}catch(Exception b) {
	    		JOptionPane.showMessageDialog(null,  "Error Close");

			}
		}

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        jLabel2.setText("    Please Select Administrator to Edit or Delete");

        closeButton.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        jLabel3.setText("User Name:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        jLabel4.setText("Password:");

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        //jTextField1.setText("   Name");

        jPasswordField1.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        jPasswordField1.setToolTipText("");
        
        JLabel lblNewLabel = new JLabel("Please fill in fields below to add new administrator");
        lblNewLabel.setFont(new Font("Lucida Grande", Font.PLAIN, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(65)
        			.addComponent(closeButton, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 1557, Short.MAX_VALUE)
        			.addComponent(addButton, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
        			.addGap(65))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(333)
        			.addComponent(adminCBox, GroupLayout.PREFERRED_SIZE, 580, GroupLayout.PREFERRED_SIZE)
        			.addGap(331))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(473)
        			.addComponent(administratorsLabel, GroupLayout.PREFERRED_SIZE, 293, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(250)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(editButton, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
        							.addGap(0, 1051, Short.MAX_VALUE)))
        					.addContainerGap(504, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(deleteButton, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel3)
        								.addComponent(jLabel4))
        							.addGap(40)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jPasswordField1, 545, 545, 545)
        								.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 545, GroupLayout.PREFERRED_SIZE))))
        					.addContainerGap(953, Short.MAX_VALUE))))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(239)
        			.addComponent(lblNewLabel)
        			.addContainerGap(944, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(21)
        			.addComponent(administratorsLabel)
        			.addGap(18)
        			.addComponent(adminCBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel2)
        			.addGap(32)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(editButton)
        				.addComponent(deleteButton))
        			.addGap(55)
        			.addComponent(lblNewLabel)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4))
        			.addPreferredGap(ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(closeButton)
        				.addComponent(addButton))
        			.addGap(14))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       // JComponent comp = (JComponent) evt.getSource();
        //Window win = SwingUtilities.getWindowAncestor(comp);
        //win.dispose();
    	
    	
   }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         JComponent comp = (JComponent) evt.getSource();
         Window win = SwingUtilities.getWindowAncestor(comp);
         win.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 EditAdmin frame = new EditAdmin();
                
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH); 
                
                frame.setVisible(true);   
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> adminCBox;
    private javax.swing.JLabel administratorsLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
}
