package cinemasystem;

import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.JComponent;
import javax.swing.SwingUtilities;

import CinemaClasses.JTextFieldLimit;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author christophermclaughlin
 */
public class Payment extends javax.swing.JFrame {

    TicketBooking Booking = new TicketBooking();
    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cardTF = new javax.swing.JTextField(19);
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        securityCodeTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cardHolderNameTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Payment");

        jLabel3.setText("Credit/Debit Card Details");

        jLabel4.setText("Your Order Total Is "+ TicketBooking.Price);

        jLabel5.setText("Card Number:");
        
        cardTF.setDocument(new JTextFieldLimit(19));
        cardTF.setForeground(new java.awt.Color(204, 204, 204));
        cardTF.setText("   Card Number");

        jLabel6.setText("Expiry:");

        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("  MM / YY");

        securityCodeTF.setDocument(new JTextFieldLimit(3));
        securityCodeTF.setForeground(new java.awt.Color(204, 204, 204));
        securityCodeTF.setText("CSC");

        jLabel7.setText("Security Code:");

        cardHolderNameTF.setForeground(new java.awt.Color(204, 204, 204));
        cardHolderNameTF.setText("  Cardholer Name");

        jLabel8.setText("Cardholder Name");

        jToggleButton1.setText("Pay Now");

        jToggleButton2.setText("Cancel");
        jToggleButton2.setMaximumSize(new java.awt.Dimension(97, 29));
        jToggleButton2.setMinimumSize(new java.awt.Dimension(97, 29));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        
        cardTF.addFocusListener(new FocusListener() {
        	public void focusGained(FocusEvent e) {
        		cardTFfocusGained(e);
        
        	}

			@Override
			public void focusLost(FocusEvent e) {
				cardTFfocusLost(e);
				
			}
        });
        
        
        securityCodeTF.addFocusListener(new FocusListener() {
        	public void focusGained(FocusEvent e) {
        		securityCodeTFfocusGained(e);
        
        	}

			@Override
			public void focusLost(FocusEvent e) {
				securityCodeTFfocusLost(e);
				
			}
        });
        
        cardHolderNameTF.addFocusListener(new FocusListener() {
        	public void focusGained(FocusEvent e) {
        		cardHolderNameTFfocusGained(e);
        
        	}

			@Override
			public void focusLost(FocusEvent e) {
				cardHolderNameTFfocusLost(e);
				
			}
        });
        
        cardTF.addKeyListener(new KeyListener() {
        	public void keyTyped(KeyEvent e) {
        		cardTFkeyTyped(e);
        	}

			@Override
			public void keyPressed(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void keyReleased(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}
        });
        
        securityCodeTF.addKeyListener(new KeyListener() {
        	public void keyTyped(KeyEvent e) {
        		securityCodeTFkeyTyped(e);
        	}

			@Override
			public void keyPressed(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void keyReleased(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}
        });
        
        cardHolderNameTF.addKeyListener(new KeyListener() {
        	public void keyTyped(KeyEvent e) {
        		cardHolderNameTFkeyTyped(e);
        	}

			@Override
			public void keyPressed(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void keyReleased(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}
        });
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cardTF)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(securityCodeTF)))
                                    .addComponent(cardHolderNameTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(cardHolderNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
         JComponent comp = (JComponent) evt.getSource();
         Window win = SwingUtilities.getWindowAncestor(comp);
         win.dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed
    
    private void cardHolderNameTFfocusGained(FocusEvent e) {
    	if(cardHolderNameTF.getText().equals("  Cardholer Name")) {
    		cardHolderNameTF.setText("");
    	}
    	
    }
    
    private void cardHolderNameTFfocusLost(FocusEvent e) {
    	if(cardHolderNameTF.getText().equals("")) {
    		cardHolderNameTF.setText("  Cardholer Name");
    	}
    	
    }
    
    private void securityCodeTFfocusGained(FocusEvent e) {
    	if(securityCodeTF.getText().equals("CSC")) {
    			securityCodeTF.setText("");
    	}
    	
    }
    
    private void securityCodeTFfocusLost(FocusEvent e) {
    	if(securityCodeTF.getText().equals("")) {
    		securityCodeTF.setText("CSC");
    	}
    	
    }
    
    private void cardTFfocusGained(FocusEvent e) {
    	if(cardTF.getText().equals("   Card Number")) {
    			cardTF.setText("");
    	}
    	
    }
    
    private void cardTFfocusLost(FocusEvent e) {
    	if(cardTF.getText().equals("")) {
    	cardTF.setText("   Card Number");
    	}
    	
    }
    
    private void cardTFkeyTyped(KeyEvent e) {
    	char c = e.getKeyChar();
    	if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE) {
    		e.consume();
    	}
    	
    }
    
    private void securityCodeTFkeyTyped(KeyEvent e) {
    	char c = e.getKeyChar();
    	if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE) {
    		e.consume();
    	}
    	
    }
    
    
    private void cardHolderNameTFkeyTyped(KeyEvent e) {
    	char c = e.getKeyChar();
    	if((Character.isDigit(c)) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE) {
    		e.consume();
    	}
    	
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField cardTF;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField securityCodeTF;
    private javax.swing.JTextField cardHolderNameTF;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
