/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemasystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;

import net.proteanit.sql.DbUtils;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextPane;

/**
 *
 * @author christophermclaughlin
 */
public class ViewInfo extends javax.swing.JFrame {

    /**
     * Creates new form ViewInfo
     */
	private final String USER_NAME = "root";
	private final String PASSWORD = "password";
    Connection conn;
    Statement st;
    ResultSet rs;
    
    public ViewInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        closeJButton = new javax.swing.JButton();
        filmName = new javax.swing.JComboBox<>();
        JLabel lblDirector = new JLabel("Directed By:");
        lblDirector.setFont(new Font("SansSerif", Font.BOLD, 20));
        lblDirector.setForeground(Color.YELLOW);
        JLabel lblGenre = new JLabel("Genre:");
        lblGenre.setFont(new Font("SansSerif", Font.BOLD, 20));
        lblGenre.setForeground(Color.YELLOW);
        JLabel lblRun = new JLabel("Run Time:");
        lblRun.setFont(new Font("SansSerif", Font.BOLD, 20));
        lblRun.setForeground(Color.YELLOW);
        lblActors = new JLabel("Actors:");
        lblActors.setFont(new Font("SansSerif", Font.BOLD, 20));
        lblActors.setForeground(Color.YELLOW);
        lblDirName = new JLabel("(Director N/A)");
        lblDirName.setFont(new Font("SansSerif", Font.BOLD, 20));
        lblDirName.setForeground(Color.YELLOW);
        sqlGenre = new JLabel("(Genre N/A)");
        sqlGenre.setFont(new Font("SansSerif", Font.BOLD, 20));
        sqlGenre.setForeground(Color.YELLOW);
        
        actorsLabel = new JLabel("(Actors N/A)");
        actorsLabel.setFont(new Font("SansSerif", Font.BOLD, 20));
        actorsLabel.setForeground(Color.YELLOW);
        
        lblRunTime = new JLabel("(Duration N/A)");
        lblRunTime.setFont(new Font("SansSerif", Font.BOLD, 20));
        lblRunTime.setForeground(Color.YELLOW);
        
        lblPgRating = new JLabel();
        lblPgRating.setFont(new Font("SansSerif", Font.BOLD, 30));
        lblPgRating.setForeground(Color.RED);
        
        synopsisTextArea = new JTextArea();
        setFont(new Font("SansSerif", Font.ITALIC, 18));
        setForeground(Color.BLACK);
        synopsisTextArea.setLineWrap(true);
        synopsisTextArea.setWrapStyleWord(true);
        //Border border = BorderFactory.createLineBorder(Color.BLACK, 5);
        //Border border = BorderFactory.createBevelBorder(5, Color.BLACK, Color.GREEN);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("View Film Info");
        jLabel1.setFont(new Font("sansserif", Font.BOLD, 24));
        jLabel1.setForeground(Color.PINK);
        //jLabel1.setBorder(border);

        closeJButton.setText("Close");
        closeJButton.setBackground(Color.RED);
        closeJButton.setFont(new Font("sansserif", Font.BOLD, 16));
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        //jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filmName.setModel(new DefaultComboBoxModel<>(new String[] {"Select Film"}));
        filmName.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		filmNameActionPerformed(e);
        
        	}
        });

        try {
			conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema?autoReconnect=true&useSSL=false", USER_NAME, PASSWORD);
			st = conn.createStatement();
			String s = "Select Name from film";
			rs = st.executeQuery(s);
			while(rs.next()) {
				filmName.addItem(rs.getString(1));
			}
		}
		catch (Exception b) {
		JOptionPane.showMessageDialog(null,  "Error");
		}finally {
			try {
				st.close();
				rs.close();
				conn.close();
				
			}catch(Exception b) {
	    		JOptionPane.showMessageDialog(null,  "Error Close");

			}
		}
        
        
        
        
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(170)
        					.addComponent(jLabel1))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(filmName, GroupLayout.PREFERRED_SIZE, 214, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(lblActors)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(actorsLabel, GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(lblDirector, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(lblDirName))
        								.addGroup(layout.createSequentialGroup()
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addGroup(layout.createParallelGroup(Alignment.LEADING)
        										.addGroup(layout.createSequentialGroup()
        											.addComponent(lblRun)
        											.addPreferredGap(ComponentPlacement.RELATED)
        											.addComponent(lblRunTime))
        										.addGroup(layout.createSequentialGroup()
        											.addComponent(lblGenre)
        											.addPreferredGap(ComponentPlacement.UNRELATED)
        											.addComponent(sqlGenre)))))
        							.addGap(328)))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(720)
        							.addComponent(lblPgRating, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(synopsisTextArea, GroupLayout.PREFERRED_SIZE, 648, GroupLayout.PREFERRED_SIZE)))))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(closeJButton, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addGap(14)
        					.addComponent(jLabel1)
        					.addGap(11)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(filmName, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        							.addGap(60)
        							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(lblActors, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        								.addComponent(actorsLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        							.addGap(30)
        							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(lblDirector, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        								.addComponent(lblDirName, GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE))
        							.addGap(26)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(lblGenre, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
        								.addComponent(sqlGenre, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE))
        							.addGap(43)
        							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(lblRun)
        								.addComponent(lblRunTime)))
        						.addComponent(lblPgRating)))
        				.addComponent(closeJButton, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addGap(102)
        					.addComponent(synopsisTextArea, GroupLayout.PREFERRED_SIZE, 353, GroupLayout.PREFERRED_SIZE)
        					.addGap(29)))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);
        getContentPane().setBackground(Color.GRAY);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void fetch() {
    	
    	filmName.setModel(new DefaultComboBoxModel<>(new String[] {"Select Film"}));

        try {
			conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema?autoReconnect=true&useSSL=false", USER_NAME, PASSWORD);
			st = conn.createStatement();
			String s = "Select Name from film";
			rs = st.executeQuery(s);
			while(rs.next()) {
				filmName.addItem(rs.getString(1));
			}
		}
		catch (Exception b) {
		JOptionPane.showMessageDialog(null,  "Error");
		}finally {
			try {
				st.close();
				rs.close();
				conn.close();
				
			}catch(Exception b) {
	    		JOptionPane.showMessageDialog(null,  "Error Close");

			}
		}
    }
    
    private void filmNameActionPerformed(ActionEvent e) {
    
    String value=(String)filmName.getSelectedItem();

  	 if(value.equals("Select Film")) {
  		 //Do Nothing
  	 }
  	 else{
  		 try {
			conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema?autoReconnect=true&useSSL=false", USER_NAME, PASSWORD);
			st = conn.createStatement();
			String ac = "Select Actor from film Where Name ='"+value+"'";
			String d = "Select Director from film Where Name ='"+value+"'";
			String g = "Select Genre from film Where Name ='"+value+"'";
			String mins = "Select Duration from film Where Name ='"+value+"'";
			String pgR = "Select PG_Rating from film Where Name ='"+value+"'";
			String synopsis = "Select synopsis from film Where Name ='"+value+"'";
			
			rs = st.executeQuery(d);
			if(rs.next())
			lblDirName.setText(rs.getString(1));
			
			rs = st.executeQuery(ac);
			if(rs.next())
			actorsLabel.setText(rs.getString(1));
			
			rs = st.executeQuery(g);
			if(rs.next())
			sqlGenre.setText(rs.getString(1));
			
			rs = st.executeQuery(pgR);
			if(rs.next())
			lblPgRating.setText(rs.getString(1));
			
			rs = st.executeQuery(mins);
			if(rs.next())
			lblRunTime.setText(rs.getString(1));
			
			rs = st.executeQuery(synopsis);
			if(rs.next())
			synopsisTextArea.setText(rs.getString(1));
		}
		catch (Exception b) {
		JOptionPane.showMessageDialog(null,  b.getMessage());
		}finally {
			try {
				st.close();
				rs.close();
				conn.close();
				
			}catch(Exception b) {
	    		JOptionPane.showMessageDialog(null,  "Error Close");

			}
		}
  		 
  	 }
    }
    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JComponent comp = (JComponent) evt.getSource();
         Window win = SwingUtilities.getWindowAncestor(comp);
         win.dispose();
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;
    private javax.swing.JComboBox<String> filmName;
    private javax.swing.JLabel jLabel1,lblDirName;
    private JLabel sqlGenre;
    private JLabel lblActors;
    private JLabel actorsLabel;
    private JLabel lblRunTime;
    private JLabel lblPgRating;
    private JTextArea synopsisTextArea;
}
